# Generated by Django 4.1.5 on 2023-01-23 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="messages",
            new_name="room",
        ),
    ]
