# Generated by Django 4.1.5 on 2023-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.PositiveBigIntegerField(),
        ),
    ]
